#!/usr/bin/env bash


# Get the current directory, where all hooks reside.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#echo $DIR


# Check for console statements.
#$DIR/console.sh

# Check for tabs.
#$DIR/tabs.sh

# Remove trailing spaces from end of line(s).
#$DIR/trailing-spaces.sh
